prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml

problemreplylist修改跑板問題，email改為自動縮減過長內容  P

---

prjIHealth/ViewModels/CBodyRecordViewModel.cs
prjIHealth/Views/Body/BMICalculator.cshtml
prjIHealth/Views/Body/TDEECalculator.cshtml
prjIHealth/Views/News/Blog.cshtml
prjIHealth/Views/News/BlogDetail.cshtml
prjIHealth/Views/Problem/ReplyProblem.cshtml
prjIHealth/Views/Shared/_Layout.cshtml
prjIHealth/Views/Student/CoachList.cshtml
prjIHealth/Views/Student/CoachMainPage.cshtml
prjIHealth/Views/Student/CourseList.cshtml
prjIHealth/Views/Student/ViewCoachDetails.cshtml

修改頁面標題; 更新TDEE計算器功能_L

---

prjIHealth/Areas/Admin/Admin_Layout.cshtml
prjIHealth/Areas/Admin/Views/Authorities/Create.cshtml
prjIHealth/Areas/Admin/Views/Authorities/Delete.cshtml
prjIHealth/Areas/Admin/Views/Authorities/Details.cshtml
prjIHealth/Areas/Admin/Views/Authorities/Edit.cshtml
prjIHealth/Areas/Admin/Views/Authorities/Index.cshtml
prjIHealth/Areas/Admin/Views/CoachManage/CoachList.cshtml
prjIHealth/Areas/Admin/Views/MemberManage/Create.cshtml
prjIHealth/Areas/Admin/Views/MemberManage/Delete.cshtml
prjIHealth/Areas/Admin/Views/MemberManage/Details.cshtml
prjIHealth/Areas/Admin/Views/MemberManage/Edit.cshtml
prjIHealth/Areas/Admin/Views/OrderManage/order.cshtml
prjIHealth/Areas/Admin/Views/ProductManage/Product.cshtml
prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml

2022/07/12
我更改各管理頁面標題及title樣式_Y

更改各管理頁面標題及title樣式_Y

---

prjIHealth/Views/News/Blog.cshtml
prjIHealth/Views/News/BlogDetail.cshtml

Blog首頁標籤外露修正
Blog和BlogDetails假資料中文化

修改Blog首頁標籤外露

---

prjIHealth/Views/Home/Index.cshtml

0713主頁商城圖片更改

---

prjIHealth/ViewModels/CBodyRecordViewModel.cs
prjIHealth/Views/Diary/DiaryMain.cshtml

修改由會員生日計算年齡的程式碼; 修改飲食日誌新增食物後更新頁面功能_L

修改由會員生日計算年齡的程式碼; 修改飲食日誌新增食物後更新頁面功能_L

---

prjIHealth/Views/Body/BMICalculator.cshtml
prjIHealth/Views/Body/TDEECalculator.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml

新增飲食紀錄和計算器的DEMO鍵_L

---

prjIHealth/Areas/Admin/Controllers/ReplyController.cs
prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml

客服系統新增篩選功能  P

---

prjIHealth/Areas/Admin/Controllers/ReplyController.cs
prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml
prjIHealth/Areas/Admin/Views/Reply/Reply.cshtml
prjIHealth/ViewModels/CProblemViewModel.cs

客服系統管理介面新增日期篩選及防呆功能 P

---

prjIHealth/Controllers/ProblemController.cs
prjIHealth/Views/Problem/CheckReply.cshtml
prjIHealth/Views/Problem/ReplyProblem.cshtml

客服系統會員介面新增功能:客服紀錄-回覆篩選;聯絡我們-清空上傳檔案   P

客服系統會員介面新增功能:客服紀錄-回覆篩選;聯絡我們-清空上傳檔案   P

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/ViewModels/CProductViewModel.cs
prjIHealth/Views/Shopping/ShowShoppingMall.cshtml

把本來的類別分類產品、顯示產品、搜尋商品改為用Ajax做法，把功能跟P融合上傳第一版_Y

把本來的類別分類產品、顯示產品、搜尋商品改為用Ajax做法，把功能跟P融合上傳第一版_Y

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/ViewModels/CAddToCartViewModel.cs
prjIHealth/ViewModels/CProductViewModel.cs
prjIHealth/Views/Shopping/ShowProductDetail.cshtml
prjIHealth/Views/Shopping/ShowShoppingMall.cshtml

0719 加上顯示產品明細，跟購物車功能結合_P+Y

---

prjIHealth/Controllers/MemberController.cs
prjIHealth/Controllers/ShoppingController.cs
prjIHealth/ViewModels/CProductViewModel.cs
prjIHealth/Views/Member/ShowTrackList.cshtml
prjIHealth/Views/Shopping/ShowProductDetail.cshtml

完成顯示追蹤清單，嘗試捉MemberID_Y

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/Views/Shopping/ShoppingCartList.cshtml

新增購物車清單頁面功能，產品增減與金額計算   P

---

prjIHealth/Controllers/MemberController.cs
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml
prjIHealth/Views/Home/Index.cshtml
prjIHealth/Views/Shared/_Layout.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CourseList.cshtml

主頁樣式修改/會員區導覽列Sticky_L

---

prjIHealth/ViewModels/CCoachResumeViewModel.cs
prjIHealth/Views/Diary/DiaryMain.cshtml
prjIHealth/Views/Home/會員專區ViewDemo.cshtml
prjIHealth/Views/Member/Edit.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CourseList.cshtml
prjIHealth/Views/Student/ViewCourseCalendar.cshtml

修改會員專區左側導覽列/ResumeVModel除錯_L

---

prjIHealth/Areas/Admin/Views/CoachManage/CoachList.cshtml
prjIHealth/Controllers/CoachController.cs
prjIHealth/Controllers/StudentController.cs
prjIHealth/Models/IHealthContext.cs
prjIHealth/Models/TCoachContact.cs
prjIHealth/Models/TContactText.cs
prjIHealth/Models/TMember.cs
prjIHealth/Models/TOrder.cs
prjIHealth/ViewModels/CContactTextViewModel.cs
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/ViewCoachDetails.cshtml

增加教練/學員聯繫留言板/完成教練個人頁功能/排課時教練課程數量加一_L

增加教練/學員聯繫留言板/完成教練個人頁功能/排課時教練課程數量加一_L

---

prjIHealth/Controllers/MemberController.cs
prjIHealth/Controllers/StudentController.cs
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Shared/_Layout.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CourseList.cshtml

加上訊息Demo鍵/刪除layout重複id/改教練個人頁連結網址_L

加上訊息Demo鍵/刪除layout重複id/改教練個人頁連結網址_L

---

prjIHealth/Controllers/MemberController.cs
prjIHealth/Startup.cs

修改未用到View的連結_L

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/ViewModels/CAddToCartViewModel.cs
prjIHealth/ViewModels/CShoppingCartItem.cs
prjIHealth/Views/Shopping/CheckOut.cshtml
prjIHealth/Views/Shopping/ShoppingCartList.cshtml
prjIHealth/Views/Shopping/ShowProductDetail.cshtml
prjIHealth/Views/Shopping/ShowShoppingMall.cshtml

商城新增結帳功能，可正常新增資料至order&orderdetail   P

商城新增結帳功能，可正常新增資料至order&orderdetail   P

---

prjIHealth/Areas/Admin/Admin_Layout.cshtml
prjIHealth/Areas/Admin/Controllers/CoachManageController.cs
prjIHealth/Areas/Admin/Views/CoachManage/RateList.cshtml
prjIHealth/Controllers/CoachController.cs
prjIHealth/Controllers/DiaryController.cs
prjIHealth/ViewModels/CDiaryViewModel.cs
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml
prjIHealth/Views/Student/CandidateList.cshtml

食物列表依使用者習慣排序/對同餐別同樣食物不做新增做數量修改/調整adminlayout失效連結/新增教練評價管理查詢功能_L

食物列表依使用者習慣排序/對同餐別同樣食物不做新增做數量修改/調整adminlayout失效連結/新增教練評價管理查詢功能_L

---

prjIHealth/Controllers/CoachController.cs
prjIHealth/Views/Coach/CoachCalendar.cshtml
prjIHealth/Views/Coach/CreateResume.cshtml
prjIHealth/Views/Coach/EditResume.cshtml
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Coach/TeachingList.cshtml
prjIHealth/Views/Member/Edit.cshtml
prjIHealth/Views/Member/OrderList.cshtml
prjIHealth/Views/Member/OrderdetailList.cshtml
prjIHealth/Views/Problem/CheckReply.cshtml
prjIHealth/Views/Shared/_Layout.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CoachList.cshtml
prjIHealth/Views/Student/CourseList.cshtml
prjIHealth/Views/Student/ViewCoachDetails.cshtml
prjIHealth/Views/Student/ViewCourseCalendar.cshtml

修改各頁面導覽列連結/更正教練行事曆連結/調整衝突_L

---

prjIHealth/Controllers/StudentController.cs
prjIHealth/Views/Student/ViewCoachDetails.cshtml

恢復教練推薦功能_L

---

prjIHealth/Controllers/ProblemController.cs
prjIHealth/Controllers/ShoppingController.cs
prjIHealth/Views/Problem/ReplyProblem.cshtml
prjIHealth/Views/Shopping/CheckOut.cshtml

客服&商城增加抓取登入者ID邏輯，結帳成功後頁面改為轉至訂單查詢   P

客服&商城增加抓取登入者ID邏輯，結帳成功後頁面改為轉至訂單查詢   P

---

prjIHealth/Hubs/ChatHub.cs
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Student/CandidateList.cshtml

教練和學員聯繫改用SignalR_L

---

prjIHealth/Views/Shared/_Layout.cshtml

修正教練專區連結_L

---

prjIHealth/Views/Student/ViewCoachDetails.cshtml

修正抓靜態變數的寫法_L

---

prjIHealth/Views/Home/Index.cshtml

首頁跑馬燈連結更新正確的_L

---

prjIHealth/Areas/Admin/Controllers/MemberManageController.cs
prjIHealth/Views/Shared/_Layout.cshtml

1.修正jay0513的密碼

---

prjIHealth/Utilities/utilities.cs

更新忘記密碼功能_J

---

prjIHealth/Controllers/ShoppingController.cs

修復商城結帳執行緒問題  P

---

prjIHealth/Views/Home/Index.cshtml

修改首頁專欄為動態生成最新三筆

---

prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml

客服系統修正AJAX回傳後顯示NULL問題  P

---

prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Student/CandidateList.cshtml

修正聊天室名稱顯示_L

---

prjIHealth/Areas/Admin/Views/MemberManage/Index.cshtml
prjIHealth/Controllers/MemberController.cs
prjIHealth/Models/TAuthority.cs
prjIHealth/Views/Member/Edit.cshtml
prjIHealth/Views/Shared/_Layout.cshtml

1.修正會員編輯頁面

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/Views/Shopping/CheckOut.cshtml

優化商城結帳驗證機制  P

---

prjIHealth/Views/Shopping/CheckOut.cshtml

結帳頁面檢核優化  P

---

prjIHealth/Views/Body/BMICalculator.cshtml
prjIHealth/Views/Body/TDEECalculator.cshtml

修正計算器驗證功能_L

---

prjIHealth/Areas/Admin/Controllers/CoachManageController.cs
prjIHealth/Areas/Admin/Views/CoachManage/RateList.cshtml
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Student/CandidateList.cshtml

修正後台教練評價排序功能/更新聯繫訊息樣式_L

---

prjIHealth/Controllers/ShoppingController.cs
prjIHealth/Views/Shopping/CheckOut.cshtml

第三方金流修改存入DB時間點  P

---

prjIHealth/Controllers/MemberController.cs
prjIHealth/Views/Shared/_Layout.cshtml

1.會員登入,重設密碼,自帶session

---

prjIHealth/Areas/Admin/Views/MemberManage/Index.cshtml

修正會員後端list列表

---

prjIHealth/Areas/Admin/Controllers/NewsManageController.cs
prjIHealth/Areas/Admin/Views/NewsManage/List.cshtml
prjIHealth/ViewModels/CNewsViewModel.cs

修改後台List樣式和ajax顯示會員名稱
新增viewmodel內容
編輯後台Controll細項顯示會員名稱
_S

修改後台List樣式和ajax顯示會員名稱

---

prjIHealth/Views/Student/CandidateList.cshtml

候選教練彈出視窗樣式修改_L

---

prjIHealth/Areas/Admin/Views/NewsManage/List.cshtml
prjIHealth/Controllers/NewsController.cs
prjIHealth/Views/News/BlogCategory.cshtml
prjIHealth/Views/News/BlogDetail.cshtml

List執行ajax動作後的UI補齊
News新增Category執行，和隨機文章
新增新view BlogCategory以應執行順暢
BlogDetail註解無功能標籤及新增隨機文章顯示

          List執行ajax動作後的UI補齊

---

prjIHealth/Views/Body/BMICalculator.cshtml
prjIHealth/Views/Body/TDEECalculator.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml

修改飲食日誌&計算器btn樣式_L

---

prjIHealth/Areas/Admin/Views/Reply/ProblemReplyList.cshtml
prjIHealth/Controllers/ProblemController.cs
prjIHealth/Views/Diary/DiaryMain.cshtml
prjIHealth/Views/Problem/CheckReply.cshtml
prjIHealth/Views/Shared/_Layout.cshtml

客服系統UX優化 ，飲食日誌alert改為sweetalert     P

客服系統UX優化 ，飲食日誌alert改為sweetalert     P

---

prjIHealth/Areas/Admin/Controllers/CoachManageController.cs
prjIHealth/Areas/Admin/Controllers/MemberManageController.cs
prjIHealth/Areas/Admin/Views/CoachManage/CoachList.cshtml
prjIHealth/Areas/Admin/Views/CoachManage/RateList.cshtml
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CourseList.cshtml
prjIHealth/Views/Student/ViewCoachDetails.cshtml

履歷關鍵字搜尋修正為不分大小寫/修改課程狀態樣式/周課表加上額滿字樣_L

履歷關鍵字搜尋修正為不分大小寫/修改課程狀態樣式/周課表加上額滿字樣_L

---

prjIHealth/Controllers/ProblemController.cs

會員專區:客服紀錄bugfix，增加where條件，只顯登入會員   P

會員專區:客服紀錄bugfix，增加where條件，只顯登入會員   P

---

prjIHealth/Controllers/DiaryController.cs
prjIHealth/Views/Diary/DiaryMain.cshtml

飲食日誌增加前年BMI對照曲線_L

---

prjIHealth/Areas/Admin/Views/CoachManage/CoachList.cshtml
prjIHealth/Areas/Admin/Views/CoachManage/RateList.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml

新增教練管理頁查詢筆數_L

---

prjIHealth/Areas/Admin/Controllers/NewsManageController.cs
prjIHealth/Areas/Admin/Views/NewsManage/Create.cshtml
prjIHealth/Areas/Admin/Views/NewsManage/Edit.cshtml
prjIHealth/Areas/Admin/Views/NewsManage/List.cshtml
prjIHealth/Controllers/NewsController.cs
prjIHealth/ViewModels/CNewsViewModel.cs
prjIHealth/Views/News/Blog.cshtml
prjIHealth/Views/News/BlogCategory.cshtml
prjIHealth/Views/News/BlogDetail.cshtml

修改全部的List型態，碰到新問題抓不到別的分類和會員名字
Create新增前端雙重防呆驗證，後台失敗
Edit新增前端雙重防呆驗證
List放棄pagedlist頁面顯示，改為前端ajax動態抓資料產生分頁
viewmodel新增了一堆看不太懂但是有用的東西
Blog前端顯示修改使用錯誤參數，已選擇類別保持明亮
BlogDetail留言板新增空值驗證，修改輸入樣式為textarea，欠留言成功彈出視窗
BlogCategory已選擇類別保持明亮
欠Blog前端動態分頁顯示
_S

修改的內容如詳細所示，因遺漏一個版本不確定會不會有衝突

---

prjIHealth/Views/Student/CandidateList.cshtml

修正教練主頁連結/夾入DB V31_L

---

prjIHealth/Controllers/CoachController.cs
prjIHealth/Controllers/DiaryController.cs
prjIHealth/Views/Diary/DiaryMain.cshtml

夾入DBV32/更新sweetalert_L

---

prjIHealth/Views/Coach/RecruitmentList.cshtml

修改招生紀錄bug_L

---

prjIHealth/ViewModels/CBodyRecordViewModel.cs

加上BodyVModel防呆_L

---

prjIHealth/Areas/Admin/Controllers/NewsManageController.cs
prjIHealth/Areas/Admin/Views/NewsManage/List.cshtml
prjIHealth/ViewModels/CNewsViewModel.cs

List顯示功能完整化，恢復顯示類別及姓名和搜尋功能
*欠Blog分頁及搜尋恢復和搜尋數量顯示*
_S

List顯示功能完整化，能顯示類別及姓名

---

prjIHealth/ViewModels/COrderViewModel.cs
prjIHealth/Views/Member/OrderList.cshtml
prjIHealth/Views/Member/OrderdetailList.cshtml
prjIHealth/Views/Shared/_Layout.cshtml

修改訂單明細的樣式_L

---

prjIHealth/Views/Member/OrderList.cshtml
prjIHealth/Views/Member/OrderdetailList.cshtml

修改訂單及訂單明細樣式_L

---

prjIHealth/Views/Diary/DiaryMain.cshtml

修改alert樣式_L

---

prjIHealth/Areas/Admin/Views/CoachManage/CoachList.cshtml
prjIHealth/Areas/Admin/Views/CoachManage/RateList.cshtml
prjIHealth/Areas/Admin/Views/NewsManage/Edit.cshtml
prjIHealth/Views/Home/Index.cshtml

修改管理區sweetalert重複宣告錯誤/移除index已刪除的css引用/更新DBV34_L

修改管理區sweetalert重複宣告錯誤/移除index已刪除的css引用/更新DBV34_L

---

prjIHealth/Areas/Admin/Views/ProductManage/ProductImgList.cshtml
prjIHealth/Views/Coach/CreateResume.cshtml
prjIHealth/Views/Coach/EditResume.cshtml
prjIHealth/Views/Shopping/ShowShoppingMall.cshtml
prjIHealth/Views/Student/CoachList.cshtml

移除sweetalertCDN引用_L

---

prjIHealth/Views/Student/ViewCoachDetails.cshtml

調整教練個人頁登入提醒位置_L

---

prjIHealth/Areas/Admin/Views/OrderManage/orderdetailedit.cshtml

修正修改明細/夾入DB V36_L

---

prjIHealth/Areas/Admin/Controllers/MemberManageController.cs
prjIHealth/Areas/Admin/Views/MemberManage/Edit.cshtml
prjIHealth/Controllers/MemberController.cs
prjIHealth/Views/Coach/CreateResume.cshtml
prjIHealth/Views/Coach/EditResume.cshtml
prjIHealth/Views/Coach/RecruitmentList.cshtml
prjIHealth/Views/Coach/TeachingList.cshtml
prjIHealth/Views/Diary/DiaryMain.cshtml
prjIHealth/Views/Home/signalRChat.cshtml
prjIHealth/Views/Home/教練專區ViewDemo.cshtml
prjIHealth/Views/Home/會員專區ViewDemo.cshtml
prjIHealth/Views/Member/Edit.cshtml
prjIHealth/Views/Member/Index.cshtml
prjIHealth/Views/Member/OrderList.cshtml
prjIHealth/Views/Member/OrderdetailList.cshtml
prjIHealth/Views/Problem/CheckReply.cshtml
prjIHealth/Views/Shared/_Layout.cshtml
prjIHealth/Views/Student/CandidateList.cshtml
prjIHealth/Views/Student/CourseList.cshtml
prjIHealth/Views/Student/ViewCourseCalendar.cshtml

修改會員專區連結/生日格式驗證

---

prjIHealth/Areas/Admin/Views/Reply/Reply.cshtml

客服回覆方式的文字內容由EAMIL改為線上回覆    P
